---
title: "EDS221-day3-tasks"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(stringr)
library(tidyverse)
```

```{r}
pm2_5 <- 48

# Write an if - else if - else statement that returns “Low to moderate risk” if pm2_5 (for Particulate Matter 2.5) is less than 100, “Unhealthy for sensitive groups” if PM 2.5 is 100 <= pm2_5 < 150, and “Health risk present” if PM 2.5 is >= 150.

if (pm2_5 < 100){
  print( "Low to Moderate Risk")
  } else if (100 < pm2_5 & pm2_5 < 150){
    print("Unhealthy for Sensitive Groups")
  } else {
    print("Health Risk Present")
    }


```

```{r}
# Store the string “blue whale” as an object called species. Write an if statement that returns “You found a whale!” if the string “whale” is detected in species, otherwise return nothing. Test by changing the species string & re-running to see output.

species <- "Blue Whale"

if(str_detect(species, "Blue Whale")) {
  print("You found a Whale!")
} else {
    print("This is NOT a Whale")}

```

```{r}
#Store the base price of a burrito as base_burrito with a value of 6.50. Store main_ingredient with a starting string of “veggie.” Write a statement that will return the price of a burrito based on what a user specifies as “main_ingredient” (either “veggie”, “chicken” or “steak”) given the following:

#A veggie burrito is the cost of a base burrito
#A chicken burrito costs 3.00 more than a base burrito
#A steak burrito costs 3.25 more than a base burrito

base_burrito <- 6.50 
main_ingredients <- "steak"

if (main_ingredients == "veggie"){
  print(base_burrito)
  } else if (main_ingredients == "chicken"){
    print(base_burrito + 3)
  } else if (main_ingredients == "steak"){
    print(base_burrito + 3.25)
  }


```

```{r}
#Create a new vector called fish that contains the values 8, 10, 12, 23 representing counts of different fish types in a fish tank (goldfish, tetras, guppies, and mollies, respectively). Write a for loop that iterates through fish, and returns what proportion of total fish in the tank are that species. Assume that these counts represent all fish in the tank.
fish_count <- c(8, 10, 12, 23)
fish_type <- c("goldfish", "tetras", "guppies", "mollies")

for (i in seq_along(fish_type)) {
  print(paste0(round((fish[i]/sum(fish_count)), 2) * 100, "% are ", fish_type[i], "."))
}


```

```{r}
#There is an existing vector in R called month.name that contains all month names (just ry running month.name in the Console to check it out). Write a for loop that iterates over all months in month.name and prints “January is month 1,” “February is month 2”, etc.

for (i in seq_along(month.name)) {
  print(paste0(month.name[i], " is month", " ", i))
  }
```

